name: Recent Activity

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  activity:
    name: Update activity
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Readme-Workflows/recent-activity@v2.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          CONFIG_FILE: "config.yml"
