name: Update README

on:
  schedule:
    - cron: '*/5 * * * *' # Update every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: Readme-Workflows/recent-activity@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "./.github/update-readme.config.yml"
